### ISSUE TITLE
How to pass AT commands to Lora from ESP32 UART?

### ISSUE THREAD

**Issue by mrnams** [bkolicoski/rylr998-lora-distance-test#1]
How to pass AT commands to Lora from ESP32 UART?
I am not able to send Address,Band, network id through program ? 
Sorry, this is not an issue, this is my problem.

**Comment by bkolicoski** [comment]
You do it exactly like I do with the NodeMCU but you will need to find a Software Serial Library that is meant to work with ESP32 boards (try this one: https://github.com/plerup/espsoftwareserial) and also make sure that the wiring is connected as stated in the sketch.
